# 异常

[try-catch到底是放循环体里面还是外面？](https://mp.weixin.qq.com/s/AbZH57nUtePC728XfCvrcw)

在没有发生异常的情况下，除去误差值，我们得到的结论是：**try-catch 无论是在 `for` 循环内还是  `for` 循环外，它们的性能相同，几乎没有任何差别**

可以看出在循环体内的 try-catch 在发生异常之后，可以继续执行循环；而循环外的 try-catch 在发生异常之后会终止循环

因此我们**在决定 try-catch 究竟是应该放在循环内还是循环外，不取决于性能（因为性能几乎相同），而是应该取决于具体的业务场景**